[UMovSpecialForcesConfig.]
m_GameDifficulty=3
m_GroundSpeedMultiplier=1.0

m_ControllerClassName="UMovSpecialForcesMod.USMC_Marine_Support_Bot"

m_OverrideAIParams=true

m_SpawnSniperRifleAtStart=true
m_SniperRifleName="VietnamWeapons.PickupM21"

m_SpawnNewWeaponAtStart=true
m_NewWeaponName="VietnamWeapons.PickupM60"
;m_NewWeaponName="UMovSpecialForcesMod.PickupM16E1"
;m_NewWeaponName="UMovSpecialForcesMod.PickupM1911Silenced"
;m_NewWeaponName="UMovSpecialForcesMod.PickupAK47Scope"
;m_NewWeaponName="UMovSpecialForcesMod.PickupM16Scope"
;m_NewWeaponName="UMovSpecialForcesMod.PickupAK47Scope"

m_DroppedAmount=3
m_RefillingCount=10
m_ReserveAmmo=999

m_bDoAI=True
m_fDamageScale=1.000000
m_bSearchableCorpse=True
m_bWoundedBehaviors=True
m_bCorpseSearch=True
bDesiredEnableEnemy=True
MinEnemyDistance=256.000000
MaxEnemyDistance=4096.000000
Threat=1.000000
ThreatRadius=2048.000000
FireWhileMovingPct=0.950000
PawnHealth=100
bSuppressAvailable=True
bGrenadeAware=True
bForceFavoriteCover=True
fPatrolDelay=5.000000
fStopAtNodeVariance=1.000000
MaxCoverLeaderDistance=2000.000000
Hearing=4096.000000
FOV=90.000000
Sight=7500.000000
bEnablePain=True
bEnableBumping=True
MaxNoticeTime=2.000000
m_fMaxNoticeTimeScale=1.000000
MinLeaderDistance=250.000000
MaxLeaderDistance=1500.000000
WaitDistance=256.000000
bLookInLeaderDir=True
m_fAccuracyMultiplier=1.000000
MinAccuracyMultiplier=0.100000
m_bChanceToHit=255
ReloadPct=0.300000
GrenThrowPct=0.350000
SquadName="USMC"
fStayBehindLeaderBias=0.250000
